Add database
nikolay-977/java-filmorate pull request #3
Opened 2022-08-06 21:36 UTC by nikolay-977

2022-08-07 15:40 UTC, Frilock requested changes
Добрый день, в целом все ОК, написал пару небольших комментариев.

2022-08-07 15:40 UTC, Frilock commented on pom.xml
> +        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
В данном случае, мне кажется вы могли бы просто тут версию назвать sourceEncoding.version и использовать в двух местах. Зачем 2 проперти с одним значением?

2022-08-07 15:40 UTC, Frilock commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS USERS
По поводу диаграммы БД, а там разве не должны еще быть связи указаны?

2022-08-07 15:40 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/FilmGenre.java
> +    Long filmId;
Модификаторы?

2022-08-07 15:40 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +    public Optional<Genre> getGenre(Long id) {
пустую строку пропустите

2022-08-07 15:40 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +        boolean isContainsId = genreStorage.getAllGenres().stream().map(Genre::getId)
map тоже лучше с новой строки.

2022-08-07 15:40 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +//        user.setId(++nextId);
Если этот код не нужен убирайте его, не оставляйте закоментированный код

2022-08-07 15:40 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +    public void addFriends(Long userId, Long friendId) {
Может быть работу с Friends вынести в отдельный storage, чтобы не путаться?

2022-08-08 20:06 UTC, nikolay-977 commented on pom.xml
> +        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
Поправил

2022-08-08 20:06 UTC, nikolay-977 commented on src/main/java/ru/yandex/practicum/filmorate/model/FilmGenre.java
> +    Long filmId;
Поправил

2022-08-08 20:06 UTC, nikolay-977 commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +    public Optional<Genre> getGenre(Long id) {
Поправил

2022-08-08 20:06 UTC, nikolay-977 commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +        boolean isContainsId = genreStorage.getAllGenres().stream().map(Genre::getId)
Поправил

2022-08-08 20:07 UTC, nikolay-977 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +//        user.setId(++nextId);
Поправил

2022-08-08 20:21 UTC, nikolay-977 commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS USERS
Связи почему-то не отображаются на картинке, но они указаны в диаграмме: https://dbdiagram.io/d/62e3c8a2f31da965e83e2d81

2022-08-09 14:43 UTC, nikolay-977 commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +    public void addFriends(Long userId, Long friendId) {
Поправил

2022-08-09 15:40 UTC, Frilock approved these changes
Принято

2022-08-09 15:40 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/RateController.java
> +    @GetMapping()
Пустые скобки можете не оставлять

2022-08-09 15:40 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +    public static final String SQL_QUERY_GET_USER_BY_ID = "SELECT * FROM USERS WHERE ID = ?";public static final String SQL_QUERY_UPDATE_USER = "UPDATE USERS " +
Форматирование сьехало

2022-08-15 16:50 UTC, merged